### ISSUE TITLE
Road runner package is not installing with python version 3.6

### ISSUE THREAD

**Issue by ahsan-javaid** [UWKM/roadrunner#1]
road runner package is not installing with python version 3.6. When I run pip install roadrunner it gives me below error.
``
`(3.6) ahsan@unassigned:~/Desktop/CMS/seo-cms$ pip install roadrunner
Collecting roadrunner
  Using cached https://files.pythonhosted.org/packages/77/af/7974c51701ffce7b26328701f473f14e1d84915ff21eadc1f27d9807a28d/roadrunner-0.2.3.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/ahsan/Desktop/CMS/3.6/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z28ihc0s/roadrunner/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z28ihc0s/roadrunner/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-z28ihc0s/roadrunner/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z28ihc0s/roadrunner/setup.py", line 18, in <module>
        file('doc.txt', 'w').write(long_description)
    NameError: name 'file' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by pdeero** [comment]
You could install it via pip install git+git://github.com/UWKM/roadrunner
